version: "3"

services:
  redis:
    image: "redis:alpine"
    command: "redis-server"
    ports:
      - "6379:6379"

  db: 
    build:
      context: .
      dockerfile: src/db/Dockerfile
    image: db:v1
    ports:
      - "50052:50052"
    volumes:
      - ./:/app
    command: "python3 ./src/db/database.py"
    depends_on: 
      - redis
    environment:
      PYTHONPATH: /app/proto
      PYTHONUNBUFFERED: 1
      
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    image: server:v1
    ports: 
      - "50051:50051"
    volumes:
      - ./:/app
    command: python3 ./src/server/server.py
    depends_on:
      - db
    environment:
      PYTHONPATH: /app/proto
      PYTHONUNBUFFERED: 1
  
  client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    image: client:v1
    ports: 
      - "50055:50055"
    volumes:
      - ./:/app
    depends_on:
      - db
      - server
    command: python3 ./src/client/client.py
    environment:
      PYTHONPATH: /app/proto
      PYTHONUNBUFFERED: 1