# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='asynch',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x06\x61synch\"&\n\x0e\x43omputeRequest\x12\x14\n\x0cworker_index\x18\x01 \x01(\x05\"\x1c\n\rDatabaseReply\x12\x0b\n\x03key\x18\x01 \x03(\t\"4\n\x0f\x44\x61tabaseRequest\x12\x0b\n\x03key\x18\x01 \x03(\t\x12\x14\n\x0cworker_index\x18\x02 \x01(\x05\"\"\n\nTrajectory\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"W\n\x04\x44\x61ta\x12(\n\x0ctrajectories\x18\x01 \x03(\x0b\x32\x12.asynch.Trajectory\x12\x0f\n\x07rewards\x18\x02 \x03(\x05\x12\x14\n\x0cworker_index\x18\x03 \x01(\x05\x32\x46\n\rDataProcessor\x12\x35\n\x0b\x43omputeData\x12\x16.asynch.ComputeRequest\x1a\x0c.asynch.Data\"\x00\x32q\n\x08\x44\x61tabase\x12\x31\n\x08SaveData\x12\x0c.asynch.Data\x1a\x15.asynch.DatabaseReply\"\x00\x12\x32\n\x07GetData\x12\x17.asynch.DatabaseRequest\x1a\x0c.asynch.Data\"\x00\x62\x06proto3')
)




_COMPUTEREQUEST = _descriptor.Descriptor(
  name='ComputeRequest',
  full_name='asynch.ComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worker_index', full_name='asynch.ComputeRequest.worker_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=60,
)


_DATABASEREPLY = _descriptor.Descriptor(
  name='DatabaseReply',
  full_name='asynch.DatabaseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='asynch.DatabaseReply.key', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=90,
)


_DATABASEREQUEST = _descriptor.Descriptor(
  name='DatabaseRequest',
  full_name='asynch.DatabaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='asynch.DatabaseRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_index', full_name='asynch.DatabaseRequest.worker_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=144,
)


_TRAJECTORY = _descriptor.Descriptor(
  name='Trajectory',
  full_name='asynch.Trajectory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='asynch.Trajectory.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='asynch.Trajectory.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=180,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='asynch.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trajectories', full_name='asynch.Data.trajectories', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rewards', full_name='asynch.Data.rewards', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worker_index', full_name='asynch.Data.worker_index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=269,
)

_DATA.fields_by_name['trajectories'].message_type = _TRAJECTORY
DESCRIPTOR.message_types_by_name['ComputeRequest'] = _COMPUTEREQUEST
DESCRIPTOR.message_types_by_name['DatabaseReply'] = _DATABASEREPLY
DESCRIPTOR.message_types_by_name['DatabaseRequest'] = _DATABASEREQUEST
DESCRIPTOR.message_types_by_name['Trajectory'] = _TRAJECTORY
DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTEREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:asynch.ComputeRequest)
  ))
_sym_db.RegisterMessage(ComputeRequest)

DatabaseReply = _reflection.GeneratedProtocolMessageType('DatabaseReply', (_message.Message,), dict(
  DESCRIPTOR = _DATABASEREPLY,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:asynch.DatabaseReply)
  ))
_sym_db.RegisterMessage(DatabaseReply)

DatabaseRequest = _reflection.GeneratedProtocolMessageType('DatabaseRequest', (_message.Message,), dict(
  DESCRIPTOR = _DATABASEREQUEST,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:asynch.DatabaseRequest)
  ))
_sym_db.RegisterMessage(DatabaseRequest)

Trajectory = _reflection.GeneratedProtocolMessageType('Trajectory', (_message.Message,), dict(
  DESCRIPTOR = _TRAJECTORY,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:asynch.Trajectory)
  ))
_sym_db.RegisterMessage(Trajectory)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:asynch.Data)
  ))
_sym_db.RegisterMessage(Data)



_DATAPROCESSOR = _descriptor.ServiceDescriptor(
  name='DataProcessor',
  full_name='asynch.DataProcessor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=271,
  serialized_end=341,
  methods=[
  _descriptor.MethodDescriptor(
    name='ComputeData',
    full_name='asynch.DataProcessor.ComputeData',
    index=0,
    containing_service=None,
    input_type=_COMPUTEREQUEST,
    output_type=_DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAPROCESSOR)

DESCRIPTOR.services_by_name['DataProcessor'] = _DATAPROCESSOR


_DATABASE = _descriptor.ServiceDescriptor(
  name='Database',
  full_name='asynch.Database',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=343,
  serialized_end=456,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaveData',
    full_name='asynch.Database.SaveData',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATABASEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetData',
    full_name='asynch.Database.GetData',
    index=1,
    containing_service=None,
    input_type=_DATABASEREQUEST,
    output_type=_DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATABASE)

DESCRIPTOR.services_by_name['Database'] = _DATABASE

# @@protoc_insertion_point(module_scope)
