# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_pb2 as data__pb2


class DataProcessorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ComputeData = channel.unary_unary(
        '/asynch.DataProcessor/ComputeData',
        request_serializer=data__pb2.ComputeRequest.SerializeToString,
        response_deserializer=data__pb2.Data.FromString,
        )


class DataProcessorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ComputeData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataProcessorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ComputeData': grpc.unary_unary_rpc_method_handler(
          servicer.ComputeData,
          request_deserializer=data__pb2.ComputeRequest.FromString,
          response_serializer=data__pb2.Data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'asynch.DataProcessor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DatabaseStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SaveData = channel.unary_unary(
        '/asynch.Database/SaveData',
        request_serializer=data__pb2.Data.SerializeToString,
        response_deserializer=data__pb2.DatabaseReply.FromString,
        )
    self.GetData = channel.unary_unary(
        '/asynch.Database/GetData',
        request_serializer=data__pb2.DatabaseRequest.SerializeToString,
        response_deserializer=data__pb2.Data.FromString,
        )


class DatabaseServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SaveData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DatabaseServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SaveData': grpc.unary_unary_rpc_method_handler(
          servicer.SaveData,
          request_deserializer=data__pb2.Data.FromString,
          response_serializer=data__pb2.DatabaseReply.SerializeToString,
      ),
      'GetData': grpc.unary_unary_rpc_method_handler(
          servicer.GetData,
          request_deserializer=data__pb2.DatabaseRequest.FromString,
          response_serializer=data__pb2.Data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'asynch.Database', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
